### ISSUE TITLE
Segfault on Ubuntu MBP

### ISSUE THREAD

**Issue by paulthomson** [graphicsfuzz/get-image-glsl#1]
I get a segfault. From memory, this is because `glGetProgramBinary` does not exist.

**Comment by hevrard** [comment]
`glGetProgramBinary` is available from OpenGL 4.1, maybe Ubuntu does not support it by default?

In any case, this needs a fix to disable this option when it's not available.

**Comment by paulthomson** [comment]
Actually, I think the function causing the issue was: `glProgramParameteri`.

**Comment by hevrard** [comment]
OK, that's because I setup an opengl context depending on the shader version, so for any shader < 410, a call to `glProgramParameteri` will segfault. I pushed a temporary fix which disallow binary dumps for such shaders, but I need to separate the shader version and OpenGL context version, to be able to dump binaries even for shader versions < 410.

**Comment by hevrard** [comment]
Fixed by: d2d418049e68a7eb5633eddecf6db29c4a348fb0
Mesa drivers do not support dumping binaries, one must check the number of binary formats supported to detect this.
